import {DEFAULT_THANKS_HINT,makeThanksText,makeMessageId,encodeThanksPayload,decodeThanksPayload,addUniqueThanks,pickByTag,localDateValue,normalizeAuthor,unreadTotal} from './app-core.mjs';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={
  get(k,d=[]){try{return JSON.parse(localStorage.getItem('us_'+k))??d}catch{return d}},
  set(k,v){try{localStorage.setItem('us_'+k,JSON.stringify(v));return true}catch{return false}}
};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1900)}

// Профиль этого устройства и индикаторы активности.
let profile=store.get('profile',{});if(!profile||typeof profile!=='object')profile={};
const sectionNames={thanks:'Спасибо',wishlist:'Хотелки',ideas:'Идеи',likes:'Нам нравится',moments:'Моменты',movies:'Фильмы'};
const storageSections={'us_thanks':'thanks','us_wishes':'wishlist','us_ideas':'ideas','us_likes':'likes','us_moments':'moments','us_movies':'movies'};
function currentAuthor(){return normalizeAuthor(profile.name||'')}
function authorLabel(x){return normalizeAuthor(x?.author||'')}
function requireAuthor(){const a=currentAuthor();if(a)return a;showProfileSetup();toast('Сначала выбери, кто ты');return ''}
function withAuthor(data){return {...data,author:currentAuthor(),createdAt:new Date().toISOString()}}
function getUnread(){const v=store.get('unread',{});return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}
function setUnread(section,count){const u=getUnread();u[section]=Math.max(0,Number(count)||0);store.set('unread',u);renderIndicators()}
function markUnread(section,count=1){const u=getUnread();u[section]=(Number(u[section])||0)+Math.max(1,Number(count)||1);store.set('unread',u);renderIndicators()}
function clearUnread(section){if(!sectionNames[section])return;const u=getUnread();if(Number(u[section])>0){u[section]=0;store.set('unread',u);renderIndicators()}}

const extraStyle=document.createElement('style');extraStyle.textContent=`
.tile{position:relative}.bottom button{position:relative}.identity-bar{margin:10px 4px 0;display:flex;align-items:center;justify-content:space-between;gap:8px}.who-btn{border:0;background:#fff;border-radius:15px;padding:10px 12px;display:flex;align-items:center;gap:8px;font-size:12px;color:#333;box-shadow:0 6px 18px rgba(35,30,25,.05);cursor:pointer}.who-btn small{color:#999}.local-pill{font-size:10px;color:#777;background:#ebe6df;border-radius:999px;padding:8px 10px;white-space:nowrap}.activity-signal{display:none;width:calc(100% - 8px);margin:10px 4px 0;border:1px solid #f1d29d;background:#fff7e8;border-radius:18px;padding:12px 14px;text-align:left;align-items:center;gap:11px;color:#574220;cursor:pointer}.activity-signal.show{display:flex}.activity-lamp{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:#ffe39c;font-size:21px;box-shadow:0 0 0 0 rgba(240,176,49,.5);animation:lampPulse 1.8s infinite}.activity-signal b{font-size:13px}.activity-signal span.txt{display:block;font-size:10px;color:#8d744b;margin-top:2px}@keyframes lampPulse{0%{box-shadow:0 0 0 0 rgba(240,176,49,.5)}70%{box-shadow:0 0 0 9px rgba(240,176,49,0)}100%{box-shadow:0 0 0 0 rgba(240,176,49,0)}}.notify-badge{position:absolute;right:10px;top:10px;min-width:22px;height:22px;padding:0 6px;border-radius:999px;background:#df5363;color:#fff;font-size:10px;font-weight:900;display:none;align-items:center;justify-content:center;box-shadow:0 4px 10px rgba(196,56,73,.28);z-index:5}.notify-badge.show{display:flex}.bottom .notify-badge{right:15px;top:3px;min-width:17px;height:17px;font-size:9px;padding:0 4px}.author-line{display:block;margin-top:4px;font-size:10px!important;color:#9a8f86!important}.profile-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:16px 0 10px}.profile-choice{border:1px solid #ece3db;background:#faf7f3;border-radius:17px;padding:16px 10px;font-weight:800;font-size:14px;cursor:pointer}.profile-note{font-size:10px!important;color:#999!important;margin-top:10px!important}.profile-custom{display:flex;gap:8px;margin-top:10px}.profile-custom input{flex:1;min-width:0;border:1px solid #e7ded6;border-radius:14px;padding:12px;font:inherit}.profile-custom button{border:0;background:#17191d;color:#fff;border-radius:14px;padding:0 14px;font-weight:800}.profile-close{display:none;margin-top:9px;width:100%;border:0;background:transparent;color:#888;padding:9px;cursor:pointer}.profile-close.show{display:block}
`;document.head.appendChild(extraStyle);

const identityBar=document.createElement('div');identityBar.className='identity-bar';identityBar.innerHTML='<button class="who-btn" id="profileButton">👤 <b id="profileName">Кто я?</b> <small>сменить</small></button><div class="local-pill">🔒 пока локально</div>';
$('#dailyQuote').after(identityBar);
const activitySignal=document.createElement('button');activitySignal.id='activitySignal';activitySignal.className='activity-signal';activitySignal.innerHTML='<span class="activity-lamp">💡</span><span><b>Есть новое</b><span class="txt" id="activityText"></span></span>';identityBar.after(activitySignal);
document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="profileSetup"><div class="modal-card"><div class="emoji">👋</div><h3>Кто сейчас здесь?</h3><p>Выбери один раз на этом телефоне. Новые записи будут подписываться этим именем.</p><div class="profile-grid"><button class="profile-choice" data-profile="Алекс">Алекс</button><button class="profile-choice" data-profile="Жена">❤️ Жена</button></div><div class="profile-custom"><input id="profileCustom" maxlength="32" placeholder="Или другое имя"><button id="profileCustomSave">OK</button></div><p class="profile-note">Это пока не аккаунт и не вход по паролю — имя хранится только в браузере этого устройства.</p><button class="profile-close" id="profileClose">Оставить как есть</button></div></div>`);
function updateProfileUI(){const a=currentAuthor();$('#profileName').textContent=a||'Кто я?';$('#profileClose').classList.toggle('show',Boolean(a))}
function showProfileSetup(){$('#profileCustom').value=currentAuthor();$('#profileSetup').classList.add('show');updateProfileUI()}
function setProfile(name){const n=normalizeAuthor(name);if(!n)return toast('Напиши имя');profile={...profile,name:n};store.set('profile',profile);updateProfileUI();$('#profileSetup').classList.remove('show');toast('Теперь записи будут от: '+n)}
$$('[data-profile]').forEach(b=>b.addEventListener('click',()=>setProfile(b.dataset.profile)));
$('#profileCustomSave').addEventListener('click',()=>setProfile($('#profileCustom').value));
$('#profileCustom').addEventListener('keydown',e=>{if(e.key==='Enter')setProfile(e.target.value)});
$('#profileClose').addEventListener('click',()=>$('#profileSetup').classList.remove('show'));
$('#profileButton').addEventListener('click',showProfileSetup);
updateProfileUI();if(!currentAuthor())showProfileSetup();

function renderIndicators(){const u=getUnread();for(const section of Object.keys(sectionNames)){const count=Math.max(0,Number(u[section])||0);$$(`[data-open="${section}"]`).forEach(tile=>{let b=tile.querySelector('.notify-badge');if(!b){b=document.createElement('span');b.className='notify-badge';tile.appendChild(b)}b.textContent=count>9?'9+':String(count);b.classList.toggle('show',count>0)});if(section==='thanks'){$$('[data-nav="thanks"]').forEach(tile=>{let b=tile.querySelector('.notify-badge');if(!b){b=document.createElement('span');b.className='notify-badge';tile.appendChild(b)}b.textContent=count>9?'9+':String(count);b.classList.toggle('show',count>0)})}}
  const total=unreadTotal(u),parts=Object.entries(sectionNames).filter(([k])=>(Number(u[k])||0)>0).map(([k,n])=>`${n}: ${u[k]}`);activitySignal.classList.toggle('show',total>0);$('#activityText').textContent=parts.join(' · ');activitySignal.dataset.section=Object.keys(sectionNames).find(k=>(Number(u[k])||0)>0)||'';
}
activitySignal.addEventListener('click',()=>{if(activitySignal.dataset.section)openScreen(activitySignal.dataset.section)});renderIndicators();

function renderSection(id){({thanks:renderThanks,wishlist:renderWishes,ideas:renderIdeas,likes:renderLikes,moments:renderMoments,movies:renderMovies}[id]?.())}
function openScreen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));clearUnread(id);scrollTo({top:0,behavior:'smooth'});renderSection(id)}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openScreen(b.dataset.open)));
$$('[data-home]').forEach(b=>b.addEventListener('click',()=>openScreen('home')));
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>openScreen(b.dataset.nav)));

const now=new Date();$('#today').textContent=now.toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'long'});$('#momentDate').value=localDateValue(now);
const quotes=['Сегодня можно ничего грандиозного. Достаточно быть на одной стороне.','Самые хорошие вещи часто выглядят как обычный кофе, обычный ужин и обычное «я дома».','Иногда лучший план — сохранить то, что уже делает нас счастливыми.','Дом — это не стены. Но красивые стены тоже не помешают 😄','Из маленьких привычек обычно и складывается то самое «нам хорошо».'];$('#dailyQuote').innerHTML='<b>Мысль дня.</b> '+quotes[(now.getDate()+now.getMonth())%quotes.length];

// Дизайны
const likedDesigns=new Set(store.get('designs',[]));
function renderDesignLikes(){$$('.design').forEach(d=>{const b=d.querySelector('.heart'),liked=likedDesigns.has(d.dataset.id);b.textContent=liked?'♥':'♡';b.classList.toggle('liked',liked)})}
$$('.design .heart').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const id=b.closest('.design').dataset.id;likedDesigns.has(id)?likedDesigns.delete(id):likedDesigns.add(id);store.set('designs',[...likedDesigns]);renderDesignLikes();toast(likedDesigns.has(id)?'Сохранил в понравившееся ❤️':'Убрал из понравившегося')}));
$$('.design').forEach(d=>d.addEventListener('click',()=>{const img=d.querySelector('img');$('#viewerImg').src=img.src;$('#viewerImg').alt=img.alt||'Идея интерьера';$('#viewerTitle').textContent=d.querySelector('.design-info b')?.textContent||'Идея интерьера';$('#designViewer').classList.add('show')}));
$('#closeViewer').addEventListener('click',()=>$('#designViewer').classList.remove('show'));$('#designViewer').addEventListener('click',e=>{if(e.target.id==='designViewer')$('#designViewer').classList.remove('show')});renderDesignLikes();

// Фильмы
const movieDb=[{t:'Стажёр',tag:'warm',d:'Добрый, спокойный фильм с юмором и приятной атмосферой.'},{t:'Повар на колёсах',tag:'warm',d:'Лёгкая история про еду, перемены и удовольствие от простых вещей.'},{t:'Всегда говори «Да»',tag:'fun',d:'Комедия про человека, который решил чаще соглашаться жизни.'},{t:'Отпуск по обмену',tag:'romance',d:'Тёплая романтическая история для спокойного вечера.'},{t:'Терминал',tag:'warm',d:'Добрый фильм с юмором и очень человечной историей.'},{t:'Зачарованная',tag:'fun',d:'Сказочная комедия с романтикой и лёгким настроением.'},{t:'Ла-Ла Ленд',tag:'romance',d:'Музыка, отношения и красивое настроение.'},{t:'Дьявол носит Prada',tag:'fun',d:'Лёгкая, яркая история о работе, стиле и выборе.'},{t:'Невероятная жизнь Уолтера Митти',tag:'warm',d:'Красивый и вдохновляющий фильм о выходе из привычной жизни.'}];
let movieFilter='all';$$('.movie-filter').forEach(b=>b.addEventListener('click',()=>{$$('.movie-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');movieFilter=b.dataset.filter}));
$('#pickMovie').addEventListener('click',()=>{const x=pickByTag(movieDb,movieFilter);if(!x)return toast('Для этого фильтра пока нет фильмов');const r=$('#movieResult');r.innerHTML='<b>'+esc(x.t)+'</b><p>'+esc(x.d)+'</p>';r.classList.add('show')});
$('#addMovie').addEventListener('click',()=>{if(!requireAuthor())return;const v=$('#movieInput').value.trim();if(!v)return toast('Напиши название');const a=store.get('movies');a.unshift(withAuthor({t:v,id:Date.now()}));if(!store.set('movies',a))return toast('Не удалось сохранить');$('#movieInput').value='';renderMovies();toast('Добавил 🎬')});
function renderMovies(){const a=store.get('movies');$('#movieList').innerHTML=a.length?a.map(x=>`<div class="feed-item"><b>🎬 ${esc(x.t)}</b><span class="author-line">${authorLabel(x)?'Добавил(а): '+esc(authorLabel(x)):'Старая запись без автора'}</span><button class="icon-btn del-movie" data-id="${x.id}" aria-label="Удалить">×</button></div>`).join(''):'<div class="empty">Пока ничего не добавлено.</div>';$$('.del-movie').forEach(b=>b.onclick=()=>{store.set('movies',a.filter(x=>String(x.id)!==b.dataset.id));renderMovies()})}

// Еда
const foodDb=[{t:'Пицца',tag:'delivery',e:'🍕',d:'Пусть сегодня будет просто и вкусно.'},{t:'Роллы',tag:'delivery',e:'🍣',d:'Вариант, когда готовить вообще не хочется.'},{t:'Паста',tag:'home',e:'🍝',d:'Можно быстро сделать дома и не усложнять.'},{t:'Картошка + что-нибудь вкусное',tag:'home',e:'🥔',d:'Домашняя классика без изобретений.'},{t:'Шаурма',tag:'fast',e:'🌯',d:'Быстро, понятно и почти всегда работает.'},{t:'Бургеры',tag:'delivery',e:'🍔',d:'Сегодня можно и так.'},{t:'Омлет / яичница',tag:'fast',e:'🍳',d:'Минимум усилий — максимум понятности.'},{t:'Блины или сырники',tag:'sweet',e:'🥞',d:'Почему бы не сделать ужин немного завтраком.'},{t:'Что-нибудь с кофе и десертом',tag:'sweet',e:'☕',d:'Иногда этого вполне достаточно.'},{t:'Домашние бутерброды',tag:'fast',e:'🥪',d:'Без кулинарного героизма.'}];
let foodFilter='all';$$('.food-filter').forEach(b=>b.addEventListener('click',()=>{$$('.food-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');foodFilter=b.dataset.filter}));
$('#pickFood').addEventListener('click',()=>{const x=pickByTag(foodDb,foodFilter);if(!x)return toast('Для этого фильтра пока нет вариантов');const r=$('#foodResult');r.innerHTML='<b>'+x.e+' '+esc(x.t)+'</b><p>'+esc(x.d)+'</p>';r.classList.add('show')});

// Спасибо
let currentThanks='',thanksBusy=false;
function updateThanksButtons(){const enabled=Boolean(currentThanks)&&!thanksBusy;$('#shareThanks').disabled=!enabled;$('#saveThanks').disabled=!enabled;$('#shareThanks').textContent=thanksBusy?'Открываю…':'Отправить 💌'}
function resetThanks(){currentThanks='';$('#thanksCustom').value='';$$('[data-thanks]').forEach(b=>b.classList.remove('active'));$('#thanksPreview').textContent=DEFAULT_THANKS_HINT;updateThanksButtons()}
function setThanks(reason){currentThanks=makeThanksText(reason,'');$('#thanksPreview').textContent=currentThanks;$('#thanksCustom').value='';$$('[data-thanks]').forEach(b=>b.classList.toggle('active',b.dataset.thanks===reason));updateThanksButtons()}
$$('[data-thanks]').forEach(b=>b.addEventListener('click',()=>setThanks(b.dataset.thanks)));
$('#thanksCustom').addEventListener('input',e=>{currentThanks=makeThanksText('',e.target.value);$$('[data-thanks]').forEach(b=>b.classList.remove('active'));$('#thanksPreview').textContent=currentThanks||DEFAULT_THANKS_HINT;updateThanksButtons()});
function saveThanks(msg,received=false,refId='',author=''){const old=store.get('thanks');const item={id:Date.now(),refId,text:msg,date:new Date().toISOString(),received,author:received?normalizeAuthor(author):currentAuthor(),createdAt:new Date().toISOString()};const next=addUniqueThanks(old,item);if(next.length===old.length)return false;if(!store.set('thanks',next)){toast('Не удалось сохранить');return false}renderThanks();return true}
$('#saveThanks').addEventListener('click',()=>{if(!currentThanks||!requireAuthor())return;saveThanks(currentThanks,false,makeMessageId());resetThanks();toast('Добавил в банку 💌')});
$('#shareThanks').addEventListener('click',async()=>{const author=requireAuthor();if(!currentThanks||thanksBusy||!author)return;thanksBusy=true;updateThanksButtons();const msg=currentThanks,id=makeMessageId(),date=new Date().toISOString();const payload=encodeThanksPayload({id,text:msg,date,author});const url=location.origin+location.pathname+'#thanks='+payload;try{if(navigator.share){await navigator.share({title:`Сообщение от ${author} ❤️`,text:msg,url});saveThanks(msg,false,id,author);resetThanks();toast('Отправлено 💌')}else if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(msg+'\n'+url);saveThanks(msg,false,id,author);resetThanks();toast('Сообщение и ссылка скопированы')}else{toast('На этом устройстве нет функции «Поделиться»')}}catch(e){if(e?.name!=='AbortError')toast('Не получилось поделиться')}finally{thanksBusy=false;updateThanksButtons()}});
function renderThanks(){const a=store.get('thanks');$('#thanksCount').textContent=a.length?a.length+' сообщений':'';$('#thanksFeed').innerHTML=a.length?a.map(x=>{const au=authorLabel(x);return `<div class="feed-item"><b>${x.received?(au?'💌 От '+esc(au):'💌 Получено'):(au?'❤️ '+esc(au):'❤️ Спасибо')}</b><p>${esc(x.text)}</p><time>${new Date(x.date).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time></div>`}).join(''):'<div class="empty">Здесь будут копиться маленькие «спасибо».</div>'}
function checkIncoming(){if(!location.hash.startsWith('#thanks='))return;try{const d=decodeThanksPayload(location.hash.slice(8));$('#receivedText').textContent=d.text;const h=$('#received .modal-card h3');if(h)h.textContent=d.author?`${d.author} говорит спасибо`:'Тебе сказали спасибо';$('#received').classList.add('show');window.__incomingThanks=d}catch{history.replaceState(null,'',location.pathname+location.search)}}
$('#closeReceived').addEventListener('click',()=>{const d=window.__incomingThanks;if(d)saveThanks(d.text,true,d.id||('legacy:'+d.date+':'+d.text),d.author);window.__incomingThanks=null;$('#received').classList.remove('show');history.replaceState(null,'',location.pathname+location.search);openScreen('thanks');toast('Сохранил сообщение ❤️')});
window.addEventListener('hashchange',checkIncoming);resetThanks();checkIncoming();

// Хотелки
$('#addWish').addEventListener('click',()=>{if(!requireAuthor())return;const t=$('#wishText').value.trim();if(!t)return toast('Напиши хотелку');const a=store.get('wishes');a.unshift(withAuthor({id:Date.now(),t,type:$('#wishType').value,done:false}));if(!store.set('wishes',a))return toast('Не удалось сохранить');$('#wishText').value='';renderWishes()});
function renderWishes(){const a=store.get('wishes');$('#wishList').innerHTML=a.length?a.map(x=>`<div class="list-item ${x.done?'done':''}"><div class="ico">${x.type}</div><div><b>${esc(x.t)}</b><span>${authorLabel(x)?esc(authorLabel(x))+' · ':''}${x.done?'исполнено':'хочется'}</span></div><div class="row"><button class="icon-btn wish-done" data-id="${x.id}">${x.done?'↩':'✓'}</button><button class="icon-btn wish-del" data-id="${x.id}">×</button></div></div>`).join(''):'<div class="empty">Хотелок пока нет. Подозрительно 😄</div>';$$('.wish-done').forEach(b=>b.onclick=()=>{const x=a.find(i=>String(i.id)===b.dataset.id);if(!x)return;x.done=!x.done;store.set('wishes',a);renderWishes()});$$('.wish-del').forEach(b=>b.onclick=()=>{store.set('wishes',a.filter(i=>String(i.id)!==b.dataset.id));renderWishes()})}

// Идеи
let ideaType='👀';$$('.idea-type').forEach(b=>b.addEventListener('click',()=>{$$('.idea-type').forEach(x=>x.classList.remove('active'));b.classList.add('active');ideaType=b.dataset.type}));
$('#addIdea').addEventListener('click',()=>{if(!requireAuthor())return;const t=$('#ideaText').value.trim();if(!t)return toast('Напиши идею');const a=store.get('ideas');a.unshift(withAuthor({id:Date.now(),t,type:ideaType,done:false}));if(!store.set('ideas',a))return toast('Не удалось сохранить');$('#ideaText').value='';renderIdeas()});
function renderIdeas(){const a=store.get('ideas');$('#ideaList').innerHTML=a.length?a.map(x=>`<div class="list-item ${x.done?'done':''}"><div class="ico">${x.type}</div><div><b>${esc(x.t)}</b><span>${authorLabel(x)?esc(authorLabel(x))+' · ':''}${x.done?'готово':'в списке'}</span></div><div class="row"><button class="icon-btn idea-done" data-id="${x.id}">${x.done?'↩':'✓'}</button><button class="icon-btn idea-del" data-id="${x.id}">×</button></div></div>`).join(''):'<div class="empty">Здесь будут жить ваши «надо бы как-нибудь...»</div>';$$('.idea-done').forEach(b=>b.onclick=()=>{const x=a.find(i=>String(i.id)===b.dataset.id);if(!x)return;x.done=!x.done;store.set('ideas',a);renderIdeas()});$$('.idea-del').forEach(b=>b.onclick=()=>{store.set('ideas',a.filter(i=>String(i.id)!==b.dataset.id));renderIdeas()})}

// Нам нравится
$('#addLike').addEventListener('click',()=>{if(!requireAuthor())return;const t=$('#likeText').value.trim();if(!t)return toast('Напиши, что нравится');const a=store.get('likes');a.unshift(withAuthor({id:Date.now(),t,type:$('#likeType').value}));if(!store.set('likes',a))return toast('Не удалось сохранить');$('#likeText').value='';renderLikes()});
function renderLikes(){const a=store.get('likes');$('#likeList').innerHTML=a.length?a.map(x=>`<div class="list-item"><div class="ico">${x.type}</div><div><b>${esc(x.t)}</b><span>${authorLabel(x)?'Добавил(а): '+esc(authorLabel(x)):'нам нравится'}</span></div><button class="icon-btn like-del" data-id="${x.id}">×</button></div>`).join(''):'<div class="empty">Пока пусто. Добавляйте сюда всё подряд.</div>';$$('.like-del').forEach(b=>b.onclick=()=>{store.set('likes',a.filter(i=>String(i.id)!==b.dataset.id));renderLikes()})}

// Моменты
function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.68))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
$('#addMoment').addEventListener('click',async()=>{if(!requireAuthor())return;const file=$('#momentPhoto').files[0],text=$('#momentText').value.trim(),date=$('#momentDate').value;if(!file)return toast('Сначала выбери фото');if(!file.type.startsWith('image/'))return toast('Нужна картинка');$('#addMoment').disabled=true;try{const img=await compressImage(file),a=store.get('moments');a.unshift(withAuthor({id:Date.now(),img,text,date}));if(!store.set('moments',a.slice(0,8)))return toast('Память браузера заполнена — удали старое фото');$('#momentPhoto').value='';$('#momentText').value='';renderMoments();toast('Момент сохранён ❤️')}catch{toast('Не удалось обработать фото')}finally{$('#addMoment').disabled=false}});
function renderMoments(){const a=store.get('moments');$('#momentGrid').innerHTML=a.length?a.map(x=>`<div class="moment"><img src="${x.img}" alt="Наш момент"><div class="moment-body"><b>${x.date?new Date(x.date+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'}):'Наш момент'}</b><p>${esc(x.text||'Без подписи')}</p><span class="author-line">${authorLabel(x)?'Добавил(а): '+esc(authorLabel(x)):'Старая запись без автора'}</span><button class="icon-btn moment-del" data-id="${x.id}">×</button></div></div>`).join(''):'<div class="empty wide-empty">Здесь пока нет фото. Первое всегда самое сложное 🙂</div>';$$('.moment-del').forEach(b=>b.onclick=()=>{store.set('moments',a.filter(i=>String(i.id)!==b.dataset.id));renderMoments()})}

// Сюрприз
const surprises=[['🤗','Обнять без причины','Никакого повода не нужно. Просто подойди и обними.'],['☕','Сделать что-нибудь приятное','Чай, кофе, вкусняшка — маленькая бытовая забота сегодня считается двойной.'],['📸','Найти старую фотографию','Отправь друг другу случайную старую фотографию, которую давно не видели.'],['💬','Сказать один комплимент','Только настоящий и конкретный: за что именно.'],['❤️','Написать «я тебя люблю»','Без объяснений и без повода. Иногда трёх слов достаточно.'],['🍫','Маленький вкусный сюрприз','Купить или оставить что-нибудь вкусное друг для друга.'],['😂','Найти что-нибудь смешное','Мем, старую историю или видео, которое точно заставит второго улыбнуться.'],['📝','Одно короткое спасибо','За совершенно обычную вещь, которую обычно не замечаем.']];
$('#surpriseBtn').addEventListener('click',()=>{const x=surprises[Math.floor(Math.random()*surprises.length)];$('#surpriseEmoji').textContent=x[0];$('#surpriseTitle').textContent=x[1];$('#surpriseText').textContent=x[2]});

// Если другая вкладка этого же браузерного профиля изменит данные, показываем лампочку.
window.addEventListener('storage',e=>{
  if(e.key==='us_profile'){profile=store.get('profile',{});updateProfileUI();return}
  if(e.key==='us_unread'){renderIndicators();return}
  const section=storageSections[e.key];if(!section)return;
  let oldItems=[],newItems=[];try{oldItems=JSON.parse(e.oldValue||'[]')||[];newItems=JSON.parse(e.newValue||'[]')||[]}catch{return}
  const oldIds=new Set(oldItems.map(x=>String(x.refId||x.id||x.createdAt||'')));
  const added=newItems.filter(x=>!oldIds.has(String(x.refId||x.id||x.createdAt||''))&&authorLabel(x)&&authorLabel(x)!==currentAuthor());
  if(added.length)markUnread(section,added.length);renderSection(section);
});

renderThanks();renderWishes();renderIdeas();renderLikes();renderMoments();renderMovies();renderIndicators();window.__appReady=true;
