import {DEFAULT_THANKS_HINT,makeThanksText,makeMessageId,encodeThanksPayload,decodeThanksPayload,addUniqueThanks,pickByTag,localDateValue} from './app-core.mjs';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const store={
  get(k,d=[]){try{return JSON.parse(localStorage.getItem('us_'+k))??d}catch{return d}},
  set(k,v){try{localStorage.setItem('us_'+k,JSON.stringify(v));return true}catch{return false}}
};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1900)}
function openScreen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.bottom button').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});({thanks:renderThanks,wishlist:renderWishes,ideas:renderIdeas,likes:renderLikes,moments:renderMoments,movies:renderMovies}[id]?.())}
$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openScreen(b.dataset.open)));
$$('[data-home]').forEach(b=>b.addEventListener('click',()=>openScreen('home')));
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>openScreen(b.dataset.nav)));

const now=new Date();$('#today').textContent=now.toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'long'});$('#momentDate').value=localDateValue(now);
const quotes=['Сегодня можно ничего грандиозного. Достаточно быть на одной стороне.','Самые хорошие вещи часто выглядят как обычный кофе, обычный ужин и обычное «я дома».','Иногда лучший план — сохранить то, что уже делает нас счастливыми.','Дом — это не стены. Но красивые стены тоже не помешают 😄','Из маленьких привычек обычно и складывается то самое «нам хорошо».'];$('#dailyQuote').innerHTML='<b>Мысль дня.</b> '+quotes[(now.getDate()+now.getMonth())%quotes.length];

// Дизайны
const likedDesigns=new Set(store.get('designs',[]));
function renderDesignLikes(){$$('.design').forEach(d=>{const b=d.querySelector('.heart'),liked=likedDesigns.has(d.dataset.id);b.textContent=liked?'♥':'♡';b.classList.toggle('liked',liked)})}
$$('.design .heart').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const id=b.closest('.design').dataset.id;likedDesigns.has(id)?likedDesigns.delete(id):likedDesigns.add(id);store.set('designs',[...likedDesigns]);renderDesignLikes();toast(likedDesigns.has(id)?'Сохранил в понравившееся ❤️':'Убрал из понравившегося')}));
$$('.design').forEach(d=>d.addEventListener('click',()=>{const img=d.querySelector('img');$('#viewerImg').src=img.src;$('#viewerImg').alt=img.alt||'Идея интерьера';$('#viewerTitle').textContent=d.querySelector('.design-info b')?.textContent||'Идея интерьера';$('#designViewer').classList.add('show')}));
$('#closeViewer').addEventListener('click',()=>$('#designViewer').classList.remove('show'));$('#designViewer').addEventListener('click',e=>{if(e.target.id==='designViewer')$('#designViewer').classList.remove('show')});renderDesignLikes();

// Фильмы
const movieDb=[{t:'Стажёр',tag:'warm',d:'Добрый, спокойный фильм с юмором и приятной атмосферой.'},{t:'Повар на колёсах',tag:'warm',d:'Лёгкая история про еду, перемены и удовольствие от простых вещей.'},{t:'Всегда говори «Да»',tag:'fun',d:'Комедия про человека, который решил чаще соглашаться жизни.'},{t:'Отпуск по обмену',tag:'romance',d:'Тёплая романтическая история для спокойного вечера.'},{t:'Терминал',tag:'warm',d:'Добрый фильм с юмором и очень человечной историей.'},{t:'Зачарованная',tag:'fun',d:'Сказочная комедия с романтикой и лёгким настроением.'},{t:'Ла-Ла Ленд',tag:'romance',d:'Музыка, отношения и красивое настроение.'},{t:'Дьявол носит Prada',tag:'fun',d:'Лёгкая, яркая история о работе, стиле и выборе.'},{t:'Невероятная жизнь Уолтера Митти',tag:'warm',d:'Красивый и вдохновляющий фильм о выходе из привычной жизни.'}];
let movieFilter='all';$$('.movie-filter').forEach(b=>b.addEventListener('click',()=>{$$('.movie-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');movieFilter=b.dataset.filter}));
$('#pickMovie').addEventListener('click',()=>{const x=pickByTag(movieDb,movieFilter);if(!x)return toast('Для этого фильтра пока нет фильмов');const r=$('#movieResult');r.innerHTML='<b>'+esc(x.t)+'</b><p>'+esc(x.d)+'</p>';r.classList.add('show')});
$('#addMovie').addEventListener('click',()=>{const v=$('#movieInput').value.trim();if(!v)return toast('Напиши название');const a=store.get('movies');a.unshift({t:v,id:Date.now()});if(!store.set('movies',a))return toast('Не удалось сохранить');$('#movieInput').value='';renderMovies();toast('Добавил 🎬')});
function renderMovies(){const a=store.get('movies');$('#movieList').innerHTML=a.length?a.map(x=>`<div class="feed-item"><b>🎬 ${esc(x.t)}</b><button class="icon-btn del-movie" data-id="${x.id}" aria-label="Удалить">×</button></div>`).join(''):'<div class="empty">Пока ничего не добавлено.</div>';$$('.del-movie').forEach(b=>b.onclick=()=>{store.set('movies',a.filter(x=>String(x.id)!==b.dataset.id));renderMovies()})}

// Еда
const foodDb=[{t:'Пицца',tag:'delivery',e:'🍕',d:'Пусть сегодня будет просто и вкусно.'},{t:'Роллы',tag:'delivery',e:'🍣',d:'Вариант, когда готовить вообще не хочется.'},{t:'Паста',tag:'home',e:'🍝',d:'Можно быстро сделать дома и не усложнять.'},{t:'Картошка + что-нибудь вкусное',tag:'home',e:'🥔',d:'Домашняя классика без изобретений.'},{t:'Шаурма',tag:'fast',e:'🌯',d:'Быстро, понятно и почти всегда работает.'},{t:'Бургеры',tag:'delivery',e:'🍔',d:'Сегодня можно и так.'},{t:'Омлет / яичница',tag:'fast',e:'🍳',d:'Минимум усилий — максимум понятности.'},{t:'Блины или сырники',tag:'sweet',e:'🥞',d:'Почему бы не сделать ужин немного завтраком.'},{t:'Что-нибудь с кофе и десертом',tag:'sweet',e:'☕',d:'Иногда этого вполне достаточно.'},{t:'Домашние бутерброды',tag:'fast',e:'🥪',d:'Без кулинарного героизма.'}];
let foodFilter='all';$$('.food-filter').forEach(b=>b.addEventListener('click',()=>{$$('.food-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');foodFilter=b.dataset.filter}));
$('#pickFood').addEventListener('click',()=>{const x=pickByTag(foodDb,foodFilter);if(!x)return toast('Для этого фильтра пока нет вариантов');const r=$('#foodResult');r.innerHTML='<b>'+x.e+' '+esc(x.t)+'</b><p>'+esc(x.d)+'</p>';r.classList.add('show')});

// Спасибо
let currentThanks='',thanksBusy=false;
function updateThanksButtons(){const enabled=Boolean(currentThanks)&&!thanksBusy;$('#shareThanks').disabled=!enabled;$('#saveThanks').disabled=!enabled;$('#shareThanks').textContent=thanksBusy?'Открываю…':'Отправить 💌'}
function resetThanks(){currentThanks='';$('#thanksCustom').value='';$$('[data-thanks]').forEach(b=>b.classList.remove('active'));$('#thanksPreview').textContent=DEFAULT_THANKS_HINT;updateThanksButtons()}
function setThanks(reason){currentThanks=makeThanksText(reason,'');$('#thanksPreview').textContent=currentThanks;$('#thanksCustom').value='';$$('[data-thanks]').forEach(b=>b.classList.toggle('active',b.dataset.thanks===reason));updateThanksButtons()}
$$('[data-thanks]').forEach(b=>b.addEventListener('click',()=>setThanks(b.dataset.thanks)));
$('#thanksCustom').addEventListener('input',e=>{currentThanks=makeThanksText('',e.target.value);$$('[data-thanks]').forEach(b=>b.classList.remove('active'));$('#thanksPreview').textContent=currentThanks||DEFAULT_THANKS_HINT;updateThanksButtons()});
function saveThanks(msg,received=false,refId=''){const old=store.get('thanks');const item={id:Date.now(),refId,text:msg,date:new Date().toISOString(),received};const next=addUniqueThanks(old,item);if(next.length===old.length)return false;if(!store.set('thanks',next)){toast('Не удалось сохранить');return false}renderThanks();return true}
$('#saveThanks').addEventListener('click',()=>{if(!currentThanks)return;saveThanks(currentThanks,false,makeMessageId());resetThanks();toast('Добавил в банку 💌')});
$('#shareThanks').addEventListener('click',async()=>{if(!currentThanks||thanksBusy)return;thanksBusy=true;updateThanksButtons();const msg=currentThanks,id=makeMessageId(),date=new Date().toISOString();const payload=encodeThanksPayload({id,text:msg,date});const url=location.origin+location.pathname+'#thanks='+payload;try{if(navigator.share){await navigator.share({title:'Тебе сообщение ❤️',text:msg,url});saveThanks(msg,false,id);resetThanks();toast('Отправлено 💌')}else if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(msg+'\n'+url);saveThanks(msg,false,id);resetThanks();toast('Сообщение и ссылка скопированы')}else{toast('На этом устройстве нет функции «Поделиться»')}}catch(e){if(e?.name!=='AbortError')toast('Не получилось поделиться')}finally{thanksBusy=false;updateThanksButtons()}});
function renderThanks(){const a=store.get('thanks');$('#thanksCount').textContent=a.length?a.length+' сообщений':'';$('#thanksFeed').innerHTML=a.length?a.map(x=>`<div class="feed-item"><b>${x.received?'💌 Получено':'❤️ Спасибо'}</b><p>${esc(x.text)}</p><time>${new Date(x.date).toLocaleString('ru-RU',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''):'<div class="empty">Здесь будут копиться маленькие «спасибо».</div>'}
function checkIncoming(){if(!location.hash.startsWith('#thanks='))return;try{const d=decodeThanksPayload(location.hash.slice(8));$('#receivedText').textContent=d.text;$('#received').classList.add('show');window.__incomingThanks=d}catch{history.replaceState(null,'',location.pathname+location.search)}}
$('#closeReceived').addEventListener('click',()=>{const d=window.__incomingThanks;if(d)saveThanks(d.text,true,d.id||('legacy:'+d.date+':'+d.text));window.__incomingThanks=null;$('#received').classList.remove('show');history.replaceState(null,'',location.pathname+location.search);openScreen('thanks');toast('Сохранил сообщение ❤️')});
resetThanks();checkIncoming();

// Хотелки
$('#addWish').addEventListener('click',()=>{const t=$('#wishText').value.trim();if(!t)return toast('Напиши хотелку');const a=store.get('wishes');a.unshift({id:Date.now(),t,type:$('#wishType').value,done:false});if(!store.set('wishes',a))return toast('Не удалось сохранить');$('#wishText').value='';renderWishes()});
function renderWishes(){const a=store.get('wishes');$('#wishList').innerHTML=a.length?a.map(x=>`<div class="list-item ${x.done?'done':''}"><div class="ico">${x.type}</div><div><b>${esc(x.t)}</b><span>${x.done?'исполнено':'хочется'}</span></div><div class="row"><button class="icon-btn wish-done" data-id="${x.id}">${x.done?'↩':'✓'}</button><button class="icon-btn wish-del" data-id="${x.id}">×</button></div></div>`).join(''):'<div class="empty">Хотелок пока нет. Подозрительно 😄</div>';$$('.wish-done').forEach(b=>b.onclick=()=>{const x=a.find(i=>String(i.id)===b.dataset.id);if(!x)return;x.done=!x.done;store.set('wishes',a);renderWishes()});$$('.wish-del').forEach(b=>b.onclick=()=>{store.set('wishes',a.filter(i=>String(i.id)!==b.dataset.id));renderWishes()})}

// Идеи
let ideaType='👀';$$('.idea-type').forEach(b=>b.addEventListener('click',()=>{$$('.idea-type').forEach(x=>x.classList.remove('active'));b.classList.add('active');ideaType=b.dataset.type}));
$('#addIdea').addEventListener('click',()=>{const t=$('#ideaText').value.trim();if(!t)return toast('Напиши идею');const a=store.get('ideas');a.unshift({id:Date.now(),t,type:ideaType,done:false});if(!store.set('ideas',a))return toast('Не удалось сохранить');$('#ideaText').value='';renderIdeas()});
function renderIdeas(){const a=store.get('ideas');$('#ideaList').innerHTML=a.length?a.map(x=>`<div class="list-item ${x.done?'done':''}"><div class="ico">${x.type}</div><div><b>${esc(x.t)}</b><span>${x.done?'готово':'в списке'}</span></div><div class="row"><button class="icon-btn idea-done" data-id="${x.id}">${x.done?'↩':'✓'}</button><button class="icon-btn idea-del" data-id="${x.id}">×</button></div></div>`).join(''):'<div class="empty">Здесь будут жить ваши «надо бы как-нибудь...»</div>';$$('.idea-done').forEach(b=>b.onclick=()=>{const x=a.find(i=>String(i.id)===b.dataset.id);if(!x)return;x.done=!x.done;store.set('ideas',a);renderIdeas()});$$('.idea-del').forEach(b=>b.onclick=()=>{store.set('ideas',a.filter(i=>String(i.id)!==b.dataset.id));renderIdeas()})}

// Нам нравится
$('#addLike').addEventListener('click',()=>{const t=$('#likeText').value.trim();if(!t)return toast('Напиши, что нравится');const a=store.get('likes');a.unshift({id:Date.now(),t,type:$('#likeType').value});if(!store.set('likes',a))return toast('Не удалось сохранить');$('#likeText').value='';renderLikes()});
function renderLikes(){const a=store.get('likes');$('#likeList').innerHTML=a.length?a.map(x=>`<div class="list-item"><div class="ico">${x.type}</div><div><b>${esc(x.t)}</b><span>нам нравится</span></div><button class="icon-btn like-del" data-id="${x.id}">×</button></div>`).join(''):'<div class="empty">Пока пусто. Добавляйте сюда всё подряд.</div>';$$('.like-del').forEach(b=>b.onclick=()=>{store.set('likes',a.filter(i=>String(i.id)!==b.dataset.id));renderLikes()})}

// Моменты
function compressImage(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.68))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
$('#addMoment').addEventListener('click',async()=>{const file=$('#momentPhoto').files[0],text=$('#momentText').value.trim(),date=$('#momentDate').value;if(!file)return toast('Сначала выбери фото');if(!file.type.startsWith('image/'))return toast('Нужна картинка');$('#addMoment').disabled=true;try{const img=await compressImage(file),a=store.get('moments');a.unshift({id:Date.now(),img,text,date});if(!store.set('moments',a.slice(0,8)))return toast('Память браузера заполнена — удали старое фото');$('#momentPhoto').value='';$('#momentText').value='';renderMoments();toast('Момент сохранён ❤️')}catch{toast('Не удалось обработать фото')}finally{$('#addMoment').disabled=false}});
function renderMoments(){const a=store.get('moments');$('#momentGrid').innerHTML=a.length?a.map(x=>`<div class="moment"><img src="${x.img}" alt="Наш момент"><div class="moment-body"><b>${x.date?new Date(x.date+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'}):'Наш момент'}</b><p>${esc(x.text||'Без подписи')}</p><button class="icon-btn moment-del" data-id="${x.id}">×</button></div></div>`).join(''):'<div class="empty wide-empty">Здесь пока нет фото. Первое всегда самое сложное 🙂</div>';$$('.moment-del').forEach(b=>b.onclick=()=>{store.set('moments',a.filter(i=>String(i.id)!==b.dataset.id));renderMoments()})}

// Сюрприз
const surprises=[['🤗','Обнять без причины','Никакого повода не нужно. Просто подойди и обними.'],['☕','Сделать что-нибудь приятное','Чай, кофе, вкусняшка — маленькая бытовая забота сегодня считается двойной.'],['📸','Найти старую фотографию','Отправь друг другу случайную старую фотографию, которую давно не видели.'],['💬','Сказать один комплимент','Только настоящий и конкретный: за что именно.'],['❤️','Написать «я тебя люблю»','Без объяснений и без повода. Иногда трёх слов достаточно.'],['🍫','Маленький вкусный сюрприз','Купить или оставить что-нибудь вкусное друг для друга.'],['😂','Найти что-нибудь смешное','Мем, старую историю или видео, которое точно заставит второго улыбнуться.'],['📝','Одно короткое спасибо','За совершенно обычную вещь, которую обычно не замечаем.']];
$('#surpriseBtn').addEventListener('click',()=>{const x=surprises[Math.floor(Math.random()*surprises.length)];$('#surpriseEmoji').textContent=x[0];$('#surpriseTitle').textContent=x[1];$('#surpriseText').textContent=x[2]});

renderThanks();renderWishes();renderIdeas();renderLikes();renderMoments();renderMovies();
