if(typeof document!=='undefined'){
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const css=document.createElement('style');css.id='ui-polish-styles';css.textContent=`
:root{--spring:cubic-bezier(.2,.8,.2,1);--soft-spring:cubic-bezier(.22,1,.36,1);--glass:rgba(255,255,255,.78)}
body{overflow-x:hidden;background:radial-gradient(circle at 10% 0%,rgba(235,218,205,.38),transparent 28%),#f6f3ef}
/* Hero: дата в нормальном потоке, поэтому пустоты между датой и заголовком больше нет. */
#home .hero{min-height:0!important;padding:18px 19px 21px!important;justify-content:flex-start!important;background-position:center 54%!important}
#home .hero-top{position:relative!important;top:auto!important;left:auto!important;right:auto!important;margin:0 0 14px!important}
#home .hero h1{margin:0!important;font-size:42px;text-shadow:0 2px 18px rgba(0,0,0,.16)}#home .hero p{margin-top:9px!important}
@media(max-width:380px){#home .hero{padding:15px 16px 18px!important;border-radius:25px!important}#home .hero-top{margin-bottom:11px!important}#home .hero h1{font-size:38px}}

.screen{transform-origin:50% 8%}.screen.active{animation:screenEnter .44s var(--soft-spring) both}@keyframes screenEnter{from{opacity:0;transform:translateY(13px) scale(.992)}to{opacity:1;transform:none}}
#home.active .hero{animation:heroEnter .6s var(--soft-spring) both}@keyframes heroEnter{from{opacity:.25;transform:translateY(-6px) scale(.985)}to{opacity:1;transform:none}}
#home.active .quote{animation:riseIn .46s .05s var(--soft-spring) both}#home.active .tile{animation:tileEnter .46s var(--soft-spring) both}
#home.active .tile:nth-child(1){animation-delay:.03s}#home.active .tile:nth-child(2){animation-delay:.06s}#home.active .tile:nth-child(3){animation-delay:.09s}#home.active .tile:nth-child(4){animation-delay:.12s}#home.active .tile:nth-child(5){animation-delay:.15s}#home.active .tile:nth-child(6){animation-delay:.18s}#home.active .tile:nth-child(7){animation-delay:.21s}#home.active .tile:nth-child(8){animation-delay:.24s}#home.active .tile:nth-child(9){animation-delay:.27s}
@keyframes tileEnter{from{opacity:0;transform:translateY(14px) scale(.97)}to{opacity:1;transform:none}}@keyframes riseIn{from{opacity:0;transform:translateY(11px)}to{opacity:1;transform:none}}

.screen-head{backdrop-filter:blur(9px);-webkit-backdrop-filter:blur(9px)}.screen-head h2{position:relative}.screen-head h2:after{content:'';display:block;width:28px;height:3px;border-radius:99px;background:linear-gradient(90deg,#d76773,#e9a76d);margin-top:5px;transform-origin:left;animation:lineGrow .45s var(--soft-spring)}@keyframes lineGrow{from{transform:scaleX(0)}to{transform:scaleX(1)}}
.card,.tile,.list-item,.feed-item,.moment,.surprise,.who-btn,.activity-signal,.design-intro,.idea-card{transition:transform .24s var(--spring),box-shadow .24s var(--spring),border-color .22s ease,background .22s ease}
.card{border:1px solid rgba(235,228,221,.7)}.tile{border:1px solid rgba(235,228,221,.55);overflow:hidden;position:relative}.tile:before{content:'';position:absolute;inset:auto -35% -75% 30%;height:90px;border-radius:50%;background:radial-gradient(circle,rgba(215,103,115,.08),transparent 65%);pointer-events:none}.tile-icon{transition:transform .28s var(--spring)}
.btn,.chip,.back,.icon-btn,.bottom button,.heart,.room-tab{position:relative;overflow:hidden;transition:transform .17s var(--spring),background .2s ease,color .2s ease,box-shadow .2s ease,opacity .2s ease}.btn:active,.chip:active,.back:active,.icon-btn:active,.bottom button:active,.heart:active,.room-tab:active{transform:scale(.94)}
@media(hover:hover){.tile:hover,.card:hover,.moment:hover,.idea-card:hover{transform:translateY(-3px);box-shadow:0 15px 34px rgba(35,30,25,.1)}.tile:hover .tile-icon{transform:translateY(-2px) scale(1.08) rotate(-2deg)}.btn:hover{transform:translateY(-1px);box-shadow:0 8px 20px rgba(23,25,29,.16)}.chip:hover{background:#f2ede7}.back:hover,.icon-btn:hover{transform:translateY(-1px)}}
.screen.active .card,.screen.active .list,.screen.active .feed,.screen.active .moment-grid,.screen.active .surprise,.screen.active .design-intro,.screen.active .design-board{animation:riseIn .4s .035s var(--soft-spring) both}.list-item,.feed-item,.moment,.idea-card{animation:itemIn .35s var(--soft-spring) both}@keyframes itemIn{from{opacity:0;transform:translateY(8px) scale(.982)}to{opacity:1;transform:none}}
.field input:focus,.field textarea:focus,.field select:focus{border-color:#d6b5a6!important;box-shadow:0 0 0 4px rgba(214,181,166,.14);background:#fff!important}.field input,.field textarea,.field select{transition:border-color .2s ease,box-shadow .2s ease,background .2s ease}
.chip.active{box-shadow:0 6px 16px rgba(24,25,29,.13)}.chip.active:after{content:'';position:absolute;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.10);right:-5px;top:-8px}
.result-box.show{animation:resultPop .35s var(--soft-spring) both}@keyframes resultPop{0%{opacity:0;transform:translateY(8px) scale(.96)}65%{transform:translateY(-2px) scale(1.01)}100%{opacity:1;transform:none}}
.picker-emoji,.surprise .emoji{filter:drop-shadow(0 7px 12px rgba(70,50,35,.10));animation:emojiFloat 3.8s ease-in-out infinite}@keyframes emojiFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-5px)}}
.overlay.show{animation:overlayIn .22s ease both;backdrop-filter:blur(6px)}.overlay.show .modal-card,.overlay.show .viewer-card{animation:modalIn .34s var(--soft-spring) both}@keyframes overlayIn{from{opacity:0}to{opacity:1}}@keyframes modalIn{from{opacity:0;transform:translateY(14px) scale(.94)}to{opacity:1;transform:none}}
.bottom{transition:transform .25s var(--spring),box-shadow .25s ease;border:1px solid rgba(255,255,255,.08)}.bottom button.active{animation:navPop .28s var(--soft-spring)}@keyframes navPop{50%{transform:scale(1.05)}100%{transform:none}}
/* Счётчики: центрирование одной цифры и 9+ одинаково аккуратное. */
.notify-badge{box-sizing:border-box!important;min-width:22px!important;width:auto!important;height:22px!important;padding:1px 6px 0!important;line-height:1!important;text-align:center!important;align-items:center!important;justify-content:center!important;font-family:Arial,sans-serif!important;font-variant-numeric:tabular-nums!important}.notify-badge.show{display:flex!important;animation:badgePop .34s var(--soft-spring)}.notify-badge:not(.show){display:none!important}.bottom .notify-badge{min-width:18px!important;height:18px!important;padding:1px 5px 0!important;right:12px!important;top:3px!important}@keyframes badgePop{0%{transform:scale(.5)}70%{transform:scale(1.14)}100%{transform:scale(1)}}
.activity-lamp{animation:lampPulse 1.8s infinite,bulbTilt 4s ease-in-out infinite}@keyframes bulbTilt{0%,100%{transform:rotate(0)}50%{transform:rotate(5deg)}}

/* Цветовой характер разделов, очень мягкий. */
#movies .picker{background:linear-gradient(145deg,#fff,#f5f2ff)}#food .picker{background:linear-gradient(145deg,#fff,#fff6e9)}#moments .card{background:linear-gradient(145deg,#fff,#fff8f8)}#wishlist .card{background:linear-gradient(145deg,#fff,#f5f8ff)}#ideas .card{background:linear-gradient(145deg,#fff,#fffbea)}#likes .card{background:linear-gradient(145deg,#fff,#f8f3ff)}#surprise .surprise{background:radial-gradient(circle at 20% 18%,#fff1d8,transparent 38%),radial-gradient(circle at 80% 82%,#f3dce2,transparent 40%),#fff}

/* Спасибо: последнее сообщение, форма, затем история. */
#thanksLatest{display:none;margin-bottom:10px;padding:13px 14px;border-radius:20px;background:linear-gradient(135deg,#fff,#fff4f5);border:1px solid #efd6d9;box-shadow:0 8px 24px rgba(181,82,96,.07)}#thanksLatest.show{display:block;animation:riseIn .35s var(--soft-spring) both}#thanksLatest .latest-label{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px;font-size:10px;font-weight:900;color:#a65762;text-transform:uppercase;letter-spacing:.04em}#thanksLatest .feed-item{margin:0;border:0;background:transparent;padding:2px 0;box-shadow:none}#thanksLatest .feed-item:after{display:none!important}
#thanks .thanks-compose{position:relative;background:linear-gradient(135deg,#f4dfe1,#fff0e4);animation:thanksGlow 7s ease-in-out infinite alternate;margin-bottom:12px}@keyframes thanksGlow{from{box-shadow:0 8px 24px rgba(176,83,96,.04)}to{box-shadow:0 13px 34px rgba(176,83,96,.13)}}#thanks .thanks-compose .big{display:inline-block;animation:letterFloat 3.6s ease-in-out infinite}@keyframes letterFloat{0%,100%{transform:translateY(0) rotate(-2deg)}50%{transform:translateY(-5px) rotate(2deg)}}#thanks #saveThanks{display:none!important}#thanks #shareThanks{width:100%;padding:14px 18px;border-radius:16px;font-size:14px}#thanks .thanks-compose .mini-note{display:none!important}#thanks .thanks-preview.preview-pop{animation:resultPop .3s var(--soft-spring)}
#thanks .thanks-bank{position:relative;overflow:hidden;padding:17px 16px 15px;margin:0 0 12px;background:linear-gradient(145deg,#fff,#fff8f3);border:1px solid #f0e4dc;box-shadow:0 10px 30px rgba(90,60,45,.07)}#thanks .thanks-bank .section-title{margin:0 0 3px;align-items:center}#thanks .thanks-bank .section-title h2{font-size:18px}#thanks .thanks-bank-note{font-size:10px;color:#9a8175;margin:0 0 11px;line-height:1.45}#thanks .thanks-bank #thanksFeed{margin-top:0}#thanks .thanks-bank.compact #thanksFeed .feed-item:nth-child(n+4){display:none}#thanks .thanks-bank .feed-item.from-partner{border-color:#efc9ce;background:linear-gradient(135deg,#fff,#fff3f4);box-shadow:0 7px 20px rgba(191,88,103,.08)}#thanks .thanks-bank .feed-item.from-partner b{color:#a54f5c}#thanks .thanks-bank .feed-item.from-partner:after{content:'для тебя';position:absolute;right:10px;top:10px;font-size:9px;font-weight:800;color:#b65e6a;background:#f9e1e4;border-radius:999px;padding:5px 8px}#thanksExpand{width:100%;border:0;background:#f4ece7;color:#6f5a50;border-radius:13px;padding:10px 12px;margin-top:9px;font-size:11px;font-weight:800;cursor:pointer}#thanksExpand[hidden]{display:none}
#thanks .thanks-sent{animation:sentButton .55s var(--soft-spring)}@keyframes sentButton{0%{transform:scale(1)}40%{transform:scale(.96)}72%{transform:scale(1.035)}100%{transform:scale(1)}}.thanks-heart{position:fixed;z-index:120;pointer-events:none;font-size:18px;animation:heartFly .8s var(--soft-spring) forwards}@keyframes heartFly{0%{opacity:0;transform:translate(-50%,0) scale(.4)}20%{opacity:1}100%{opacity:0;transform:translate(calc(-50% + var(--dx)),var(--dy)) scale(1.15) rotate(var(--rot))}}

.tap-ripple{position:absolute;border-radius:50%;background:rgba(255,255,255,.32);pointer-events:none;transform:translate(-50%,-50%) scale(0);animation:ripple .48s ease-out forwards;z-index:20}@keyframes ripple{to{transform:translate(-50%,-50%) scale(1);opacity:0}}
.ui-pop{animation:resultPop .35s var(--soft-spring)!important}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.001ms!important}}
`;document.head.appendChild(css);

let bankExpanded=false;
function pop(el){if(!el)return;el.classList.remove('ui-pop');void el.offsetWidth;el.classList.add('ui-pop');setTimeout(()=>el.classList.remove('ui-pop'),450)}
function animateThanksSend(btn){btn.classList.remove('thanks-sent');void btn.offsetWidth;btn.classList.add('thanks-sent');const r=btn.getBoundingClientRect(),hearts=['❤️','💗','✨','💌','💕'];for(let i=0;i<7;i++){const h=document.createElement('span');h.className='thanks-heart';h.textContent=hearts[i%hearts.length];h.style.left=(r.left+r.width/2)+'px';h.style.top=(r.top+r.height/2)+'px';h.style.setProperty('--dx',`${-78+Math.random()*156}px`);h.style.setProperty('--dy',`${-55-Math.random()*85}px`);h.style.setProperty('--rot',`${-30+Math.random()*60}deg`);h.style.animationDelay=`${i*25}ms`;document.body.appendChild(h);setTimeout(()=>h.remove(),1000)}}
function isPartnerCard(x){const me=($('#profileName')?.textContent||'').trim(),head=(x.querySelector('b')?.textContent||'').trim();return head.startsWith('💌 От ')||(me&&!head.includes(me)&&head.startsWith('💌'))}
function refreshThanksBank(){const bank=$('#thanksBank'),feed=$('#thanksFeed'),expand=$('#thanksExpand'),latest=$('#thanksLatest');if(!bank||!feed||!expand||!latest)return;const items=$$('#thanksFeed .feed-item');items.forEach(x=>x.classList.toggle('from-partner',isPartnerCard(x)));bank.classList.toggle('compact',!bankExpanded);expand.hidden=items.length<=3;expand.textContent=bankExpanded?'Свернуть историю':'Показать всю историю · '+items.length;const first=items[0];if(first){const clone=first.cloneNode(true);clone.classList.remove('from-partner');latest.querySelector('.latest-body').replaceChildren(clone);latest.querySelector('.latest-label span').textContent=isPartnerCard(first)?'Новое для тебя':'Последнее сообщение';latest.classList.add('show')}else{latest.classList.remove('show');latest.querySelector('.latest-body').replaceChildren()}}
function setupThanks(){const thanks=$('#thanks'),hero=thanks?.querySelector('.thanks-hero'),feed=$('#thanksFeed');if(!thanks||!hero||!feed||$('#thanksBank'))return;hero.classList.add('thanks-compose');hero.querySelector('.mini-note')?.remove();const latest=document.createElement('div');latest.id='thanksLatest';latest.innerHTML='<div class="latest-label"><span>Последнее сообщение</span><b>💌</b></div><div class="latest-body"></div>';hero.before(latest);const title=[...thanks.querySelectorAll('.section-title')].find(x=>x.querySelector('#thanksCount')),bank=document.createElement('div');bank.id='thanksBank';bank.className='thanks-bank card compact';if(title){title.querySelector('h2').textContent='История «спасибо»';bank.appendChild(title)}const note=document.createElement('div');note.className='thanks-bank-note';note.textContent='Все ваши благодарности в одном месте.';bank.appendChild(note);bank.appendChild(feed);const expand=document.createElement('button');expand.id='thanksExpand';expand.type='button';expand.textContent='Показать всю историю';bank.appendChild(expand);hero.after(bank);expand.addEventListener('click',()=>{bankExpanded=!bankExpanded;refreshThanksBank();pop(bank)});const save=$('#saveThanks');if(save){save.tabIndex=-1;save.setAttribute('aria-hidden','true')}new MutationObserver(refreshThanksBank).observe(feed,{childList:true,subtree:true,characterData:true});refreshThanksBank()}
function setupCopy(){const husband=$('[data-profile="Алекс"]');if(husband){husband.dataset.profile='Муж';husband.textContent='💙 Муж'}const moments=$('#moments');if(moments){const sub=moments.querySelector('.screen-head p');if(sub)sub.textContent='Ваши общие фото и воспоминания';const note=moments.querySelector('.mini-note');if(note)note.textContent='Фото сжимается перед загрузкой и в общем режиме сохраняется в приватном хранилище.'}}
function setupResultAnimations(){['#movieResult','#foodResult','#thanksPreview','#surpriseTitle','#surpriseText'].forEach(sel=>{const el=$(sel);if(!el)return;new MutationObserver(()=>{if(sel==='#thanksPreview'){el.classList.remove('preview-pop');void el.offsetWidth;el.classList.add('preview-pop')}else pop(el)}).observe(el,{childList:true,subtree:true,characterData:true})})}
function fixBadges(){ $$('.notify-badge').forEach(b=>{if((b.textContent||'').trim()==='0')b.classList.remove('show')}) }
function setupRipple(){document.addEventListener('pointerdown',e=>{const el=e.target.closest?.('.btn,.chip,.tile,.bottom button,.back,.icon-btn,.room-tab');if(!el||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=el.getBoundingClientRect(),d=Math.max(r.width,r.height)*1.55,s=document.createElement('span');s.className='tap-ripple';s.style.width=s.style.height=d+'px';s.style.left=(e.clientX-r.left)+'px';s.style.top=(e.clientY-r.top)+'px';el.appendChild(s);setTimeout(()=>s.remove(),520)},true)}
function stagger(){const apply=root=>root.querySelectorAll?.('.list-item,.feed-item,.moment,.idea-card').forEach((x,i)=>x.style.animationDelay=Math.min(i,8)*.025+'s');apply(document);new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(n=>{if(n.nodeType===1)apply(n.parentElement||n)}))).observe(document.body,{childList:true,subtree:true})}
document.addEventListener('click',e=>{const send=e.target?.closest?.('#shareThanks');if(!send||send.disabled)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();const save=$('#saveThanks');if(save&&!save.disabled){animateThanksSend(send);save.click();setTimeout(refreshThanksBank,0)}},true);
function init(){setupCopy();setupThanks();setupResultAnimations();setupRipple();stagger();fixBadges();new MutationObserver(fixBadges).observe(document.body,{childList:true,subtree:true,characterData:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
}
