-- Movie catalog used by the shared "Что посмотреть" picker.
-- Catalog rows are server-only; the public client accesses them through family-api.
create table if not exists public.movie_catalog (
  id bigint generated by default as identity primary key,
  source text not null default 'imdb_top_1000_cc0',
  source_key text not null unique,
  title text not null,
  title_ru text,
  year integer,
  genres text[] not null default '{}',
  imdb_rating numeric(3,1) not null,
  description text not null default '',
  description_ru text,
  poster_url text,
  votes integer,
  created_at timestamptz not null default now()
);

create index if not exists movie_catalog_rating_idx
  on public.movie_catalog (imdb_rating desc, votes desc nulls last);

create table if not exists public.movie_family_status (
  movie_id bigint primary key references public.movie_catalog(id) on delete cascade,
  status text not null check (status in ('watched','hidden')),
  marked_by text not null,
  updated_at timestamptz not null default now()
);

alter table public.movie_catalog enable row level security;
alter table public.movie_family_status enable row level security;
revoke all on table public.movie_catalog from anon, authenticated;
revoke all on table public.movie_family_status from anon, authenticated;
